In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df=pd.read_csv('weather.csv')
df

,Unnamed: 0,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,...,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,0.0,No
1,1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,...,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,0.0,No
2,2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,...,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,0.0,No
3,3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,...,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,1.0,No
4,4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,...,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,0.2,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,24995,2013-03-09,Penrith,16.5,30.0,0.0,NaN,NaN,NE,26.0,...,41.0,NaN,NaN,NaN,NaN,21.6,29.4,No,0.0,No
24996,24996,2013-03-10,Penrith,16.7,30.5,0.0,NaN,NaN,NE,24.0,...,44.0,NaN,NaN,NaN,NaN,21.3,29.0,No,0.0,No
24997,24997,2013-03-11,Penrith,18.3,29.8,0.0,NaN,NaN,ENE,26.0,...,49.0,NaN,NaN,NaN,NaN,20.6,28.2,No,0.0,No
24998,24998,2013-03-12,Penrith,17.5,28.1,0.0,NaN,NaN,NNE,22.0,...,54.0,NaN,NaN,NaN,NaN,21.2,26.8,No,0.0,No
24999,24999,2013-03-13,Penrith,15.4,30.9,0.0,NaN,NaN,NE,24.0,...,39.0,NaN,NaN,NaN,NaN,20.0,30.3,No,0.0,No

In [3]:
df.isnull().sum()

Unnamed: 0           0
Date                 0
Location             0
MinTemp            331
MaxTemp            176
Rainfall           279
Evaporation      15568
Sunshine         18336
WindGustDir       3457
WindGustSpeed     3455
WindDir9am        3072
WindDir3pm        1733
WindSpeed9am       572
WindSpeed3pm      1230
Humidity9am        391
Humidity3pm       1064
Pressure9am       4828
Pressure3pm       4827
Cloud9am         10864
Cloud3pm         11185
Temp9am            245
Temp3pm            918
RainToday          279
RISK_MM              0
RainTomorrow         0
dtype: int64

In [4]:
null_percantage=(df.isnull().sum())/(df.shape[0])*100

In [5]:
null_percantage

Unnamed: 0        0.000
Date              0.000
Location          0.000
MinTemp           1.324
MaxTemp           0.704
Rainfall          1.116
Evaporation      62.272
Sunshine         73.344
WindGustDir      13.828
WindGustSpeed    13.820
WindDir9am       12.288
WindDir3pm        6.932
WindSpeed9am      2.288
WindSpeed3pm      4.920
Humidity9am       1.564
Humidity3pm       4.256
Pressure9am      19.312
Pressure3pm      19.308
Cloud9am         43.456
Cloud3pm         44.740
Temp9am           0.980
Temp3pm           3.672
RainToday         1.116
RISK_MM           0.000
RainTomorrow      0.000
dtype: float64

In [6]:
columns_with_less_nulls = null_percantage[null_percantage < 40].index

In [7]:
df_new=df[columns_with_less_nulls]
df_new

,Unnamed: 0,Date,Location,MinTemp,MaxTemp,Rainfall,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,0,2008-12-01,Albury,13.4,22.9,0.6,W,44.0,W,WNW,...,24.0,71.0,22.0,1007.7,1007.1,16.9,21.8,No,0.0,No
1,1,2008-12-02,Albury,7.4,25.1,0.0,WNW,44.0,NNW,WSW,...,22.0,44.0,25.0,1010.6,1007.8,17.2,24.3,No,0.0,No
2,2,2008-12-03,Albury,12.9,25.7,0.0,WSW,46.0,W,WSW,...,26.0,38.0,30.0,1007.6,1008.7,21.0,23.2,No,0.0,No
3,3,2008-12-04,Albury,9.2,28.0,0.0,NE,24.0,SE,E,...,9.0,45.0,16.0,1017.6,1012.8,18.1,26.5,No,1.0,No
4,4,2008-12-05,Albury,17.5,32.3,1.0,W,41.0,ENE,NW,...,20.0,82.0,33.0,1010.8,1006.0,17.8,29.7,No,0.2,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,24995,2013-03-09,Penrith,16.5,30.0,0.0,NE,26.0,SSE,NE,...,7.0,87.0,41.0,NaN,NaN,21.6,29.4,No,0.0,No
24996,24996,2013-03-10,Penrith,16.7,30.5,0.0,NE,24.0,ESE,N,...,6.0,84.0,44.0,NaN,NaN,21.3,29.0,No,0.0,No
24997,24997,2013-03-11,Penrith,18.3,29.8,0.0,ENE,26.0,NaN,ESE,...,6.0,98.0,49.0,NaN,NaN,20.6,28.2,No,0.0,No
24998,24998,2013-03-12,Penrith,17.5,28.1,0.0,NNE,22.0,S,NE,...,7.0,90.0,54.0,NaN,NaN,21.2,26.8,No,0.0,No
24999,24999,2013-03-13,Penrith,15.4,30.9,0.0,NE,24.0,NE,NE,...,11.0,88.0,39.0,NaN,NaN,20.0,30.3,No,0.0,No

**Another Methode**

In [9]:
df1=pd.DataFrame()
for i in df.columns:
    if null_percantage[i]<40:
        df1[i]=df[i]

In [10]:
df1

,Unnamed: 0,Date,Location,MinTemp,MaxTemp,Rainfall,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,0,2008-12-01,Albury,13.4,22.9,0.6,W,44.0,W,WNW,...,24.0,71.0,22.0,1007.7,1007.1,16.9,21.8,No,0.0,No
1,1,2008-12-02,Albury,7.4,25.1,0.0,WNW,44.0,NNW,WSW,...,22.0,44.0,25.0,1010.6,1007.8,17.2,24.3,No,0.0,No
2,2,2008-12-03,Albury,12.9,25.7,0.0,WSW,46.0,W,WSW,...,26.0,38.0,30.0,1007.6,1008.7,21.0,23.2,No,0.0,No
3,3,2008-12-04,Albury,9.2,28.0,0.0,NE,24.0,SE,E,...,9.0,45.0,16.0,1017.6,1012.8,18.1,26.5,No,1.0,No
4,4,2008-12-05,Albury,17.5,32.3,1.0,W,41.0,ENE,NW,...,20.0,82.0,33.0,1010.8,1006.0,17.8,29.7,No,0.2,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,24995,2013-03-09,Penrith,16.5,30.0,0.0,NE,26.0,SSE,NE,...,7.0,87.0,41.0,NaN,NaN,21.6,29.4,No,0.0,No
24996,24996,2013-03-10,Penrith,16.7,30.5,0.0,NE,24.0,ESE,N,...,6.0,84.0,44.0,NaN,NaN,21.3,29.0,No,0.0,No
24997,24997,2013-03-11,Penrith,18.3,29.8,0.0,ENE,26.0,NaN,ESE,...,6.0,98.0,49.0,NaN,NaN,20.6,28.2,No,0.0,No
24998,24998,2013-03-12,Penrith,17.5,28.1,0.0,NNE,22.0,S,NE,...,7.0,90.0,54.0,NaN,NaN,21.2,26.8,No,0.0,No
24999,24999,2013-03-13,Penrith,15.4,30.9,0.0,NE,24.0,NE,NE,...,11.0,88.0,39.0,NaN,NaN,20.0,30.3,No,0.0,No

In [11]:
df1.columns

Index(['Unnamed: 0', 'Date', 'Location', 'MinTemp', 'MaxTemp', 'Rainfall',
       'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Temp9am', 'Temp3pm', 'RainToday',
       'RISK_MM', 'RainTomorrow'],
      dtype='object')

In [12]:
df1.drop(["Unnamed: 0",'Date'],axis=1,inplace=True)

In [13]:
df["Location"].value_counts()

Location
Albury           3011
Cobar            2988
NorfolkIsland    2964
Newcastle        2955
CoffsHarbour     2953
NorahHead        2929
BadgerysCreek    2928
Moree            2854
Penrith          1418
Name: count, dtype: int64

In [14]:
df["WindGustDir"].nunique()

16

In [15]:
df["WindDir9am"].nunique()

16

In [16]:
df["WindDir3pm"].nunique()

16

In [17]:
df1.drop(["WindDir9am","WindDir3pm"],axis=1,inplace=True)
df1

,Location,MinTemp,MaxTemp,Rainfall,WindGustDir,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,Albury,13.4,22.9,0.6,W,44.0,20.0,24.0,71.0,22.0,1007.7,1007.1,16.9,21.8,No,0.0,No
1,Albury,7.4,25.1,0.0,WNW,44.0,4.0,22.0,44.0,25.0,1010.6,1007.8,17.2,24.3,No,0.0,No
2,Albury,12.9,25.7,0.0,WSW,46.0,19.0,26.0,38.0,30.0,1007.6,1008.7,21.0,23.2,No,0.0,No
3,Albury,9.2,28.0,0.0,NE,24.0,11.0,9.0,45.0,16.0,1017.6,1012.8,18.1,26.5,No,1.0,No
4,Albury,17.5,32.3,1.0,W,41.0,7.0,20.0,82.0,33.0,1010.8,1006.0,17.8,29.7,No,0.2,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,Penrith,16.5,30.0,0.0,NE,26.0,2.0,7.0,87.0,41.0,NaN,NaN,21.6,29.4,No,0.0,No
24996,Penrith,16.7,30.5,0.0,NE,24.0,4.0,6.0,84.0,44.0,NaN,NaN,21.3,29.0,No,0.0,No
24997,Penrith,18.3,29.8,0.0,ENE,26.0,0.0,6.0,98.0,49.0,NaN,NaN,20.6,28.2,No,0.0,No
24998,Penrith,17.5,28.1,0.0,NNE,22.0,4.0,7.0,90.0,54.0,NaN,NaN,21.2,26.8,No,0.0,No
24999,Penrith,15.4,30.9,0.0,NE,24.0,4.0,11.0,88.0,39.0,NaN,NaN,20.0,30.3,No,0.0,No

In [18]:
One_hot_cols=["Location","WindGustDir","RainToday"]

In [19]:
df1.isnull().sum()

Location            0
MinTemp           331
MaxTemp           176
Rainfall          279
WindGustDir      3457
WindGustSpeed    3455
WindSpeed9am      572
WindSpeed3pm     1230
Humidity9am       391
Humidity3pm      1064
Pressure9am      4828
Pressure3pm      4827
Temp9am           245
Temp3pm           918
RainToday         279
RISK_MM             0
RainTomorrow        0
dtype: int64

In [20]:
df1.select_dtypes(include=['int64','float64']).columns

Index(['MinTemp', 'MaxTemp', 'Rainfall', 'WindGustSpeed', 'WindSpeed9am',
       'WindSpeed3pm', 'Humidity9am', 'Humidity3pm', 'Pressure9am',
       'Pressure3pm', 'Temp9am', 'Temp3pm', 'RISK_MM'],
      dtype='object')

In [21]:
df1.select_dtypes(include=["object"]).columns

Index(['Location', 'WindGustDir', 'RainToday', 'RainTomorrow'], dtype='object')

In [22]:
categoric_null=['WindGustDir', 'RainToday']

In [23]:
numeric_null=['MinTemp', 'MaxTemp', 'Rainfall', 'WindGustSpeed', 'WindSpeed9am',
       'WindSpeed3pm', 'Humidity9am', 'Humidity3pm', 'Pressure9am',
       'Pressure3pm', 'Temp9am', 'Temp3pm']

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X=df1.iloc[:,:16]
X

,Location,MinTemp,MaxTemp,Rainfall,WindGustDir,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RainToday,RISK_MM
0,Albury,13.4,22.9,0.6,W,44.0,20.0,24.0,71.0,22.0,1007.7,1007.1,16.9,21.8,No,0.0
1,Albury,7.4,25.1,0.0,WNW,44.0,4.0,22.0,44.0,25.0,1010.6,1007.8,17.2,24.3,No,0.0
2,Albury,12.9,25.7,0.0,WSW,46.0,19.0,26.0,38.0,30.0,1007.6,1008.7,21.0,23.2,No,0.0
3,Albury,9.2,28.0,0.0,NE,24.0,11.0,9.0,45.0,16.0,1017.6,1012.8,18.1,26.5,No,1.0
4,Albury,17.5,32.3,1.0,W,41.0,7.0,20.0,82.0,33.0,1010.8,1006.0,17.8,29.7,No,0.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,Penrith,16.5,30.0,0.0,NE,26.0,2.0,7.0,87.0,41.0,NaN,NaN,21.6,29.4,No,0.0
24996,Penrith,16.7,30.5,0.0,NE,24.0,4.0,6.0,84.0,44.0,NaN,NaN,21.3,29.0,No,0.0
24997,Penrith,18.3,29.8,0.0,ENE,26.0,0.0,6.0,98.0,49.0,NaN,NaN,20.6,28.2,No,0.0
24998,Penrith,17.5,28.1,0.0,NNE,22.0,4.0,7.0,90.0,54.0,NaN,NaN,21.2,26.8,No,0.0
24999,Penrith,15.4,30.9,0.0,NE,24.0,4.0,11.0,88.0,39.0,NaN,NaN,20.0,30.3,No,0.0

In [26]:
y=df1.iloc[:,-1]
y

0        No
1        No
2        No
3        No
4        No
         ..
24995    No
24996    No
24997    No
24998    No
24999    No
Name: RainTomorrow, Length: 25000, dtype: object

In [27]:
df1["RainToday"].isnull().sum()

279

In [28]:
from sklearn.impute import SimpleImputer

In [29]:
si=SimpleImputer(strategy="most_frequent")
rain=si.fit_transform(df1[["RainToday"]])

In [30]:
rain

array([['No'],
       ['No'],
       ['No'],
       ...,
       ['No'],
       ['No'],
       ['No']], dtype=object)

In [31]:
df1["RainToday"]=pd.DataFrame(rain)

In [32]:
df1["RainToday"].isnull().sum()

0

In [33]:
wind=si.fit_transform(df1[["WindGustDir"]])

In [34]:
df1["WindGustDir"]=pd.DataFrame(wind)

In [35]:
df1["WindGustDir"].isnull().sum()

0

In [36]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.2,random_state=42)

In [37]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OrdinalEncoder

In [38]:
from sklearn.compose import ColumnTransformer

In [39]:
transformer=ColumnTransformer(transformers=[
    ("tnf1",SimpleImputer(),numeric_null),
    ("tnf2",OneHotEncoder(drop='first',sparse_output=False),One_hot_cols)],remainder="passthrough"
)

In [40]:
X_train_transform=transformer.fit_transform(X_train)
X_test_transform=transformer.transform(X_test)

In [41]:
X_train_transform.shape

(20000, 39)

In [42]:
Labelencoder=LabelEncoder()

In [43]:
y_train_transform=Labelencoder.fit_transform(y_train)
y_test_transform=Labelencoder.transform(y_test)

In [44]:
from sklearn.preprocessing import StandardScaler

In [45]:
scale=StandardScaler()

In [46]:
X_train_scaled=scale.fit_transform(X_train_transform)
X_test_scaled=scale.transform(X_test_transform)

In [47]:
from sklearn.ensemble import RandomForestClassifier

In [48]:
RF=RandomForestClassifier()

In [49]:
RF.fit(X_train_scaled,y_train_transform)

RandomForestClassifier()

In [50]:
#X_train_scaled = pd.DataFrame(X_train_scaled, columns=transformer.get_feature_names_out())   #to convert back into dataframe with column name
#X_test_scaled = pd.DataFrame(X_test_scaled, columns=transformer.get_feature_names_out())

In [51]:
y_pred=RF.predict(X_test_scaled)

In [52]:
y_pred

array([0, 0, 1, ..., 0, 1, 0])

In [53]:
from sklearn.metrics import accuracy_score

In [54]:
accuracy_score(y_test_transform,y_pred)

0.9998

**USING PCA ,To avoid overfiting,it is a feature extraction technique**

In [56]:
from sklearn.decomposition import PCA

In [57]:
Pca=PCA(n_components=3)

In [58]:
X_train_pca=Pca.fit_transform(X_train_scaled)
X_test_pca=Pca.transform(X_test_scaled)

In [59]:
RF.fit(X_train_pca,y_train_transform)

RandomForestClassifier()

In [60]:
y_pred=RF.predict(X_test_pca)

In [61]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [62]:
accuracy_score(y_test_transform,y_pred)

0.814